name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      BUILD_DIR: cmake-build
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Setup MSVC (Windows only)
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0
        with:
          msbuild-architecture: x64
      - name: Build
        run: |
          cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=Release
          cmake --build ${{ env.BUILD_DIR }} --target BeamSynth_All --config Release

      - name: Packaging (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          ZIP_FILE_NAME=BeamSynth_${{ matrix.os }}.zip
          BUILD_OUTPUT_PATH=${{ env.BUILD_DIR }}/src/BeamSynth_artefacts/Release

          current_dir=$(pwd)
          cd $BUILD_OUTPUT_PATH
          zip -r "$ZIP_FILE_NAME" *
          mv $ZIP_FILE_NAME $current_dir
      - name: Packaging (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pwsh -command "Compress-Archive -Path ${{ env.BUILD_DIR }}\\src\\BeamSynth_artefacts\\Release\\* -DestinationPath BeamSynth_${{ matrix.os }}.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: BeamSynth-${{ matrix.os }}
          path: BeamSynth_${{ matrix.os }}.zip
